### PR TITLE
Update dependencies

### LINKED ISSUE #118: An in-range update of semantic-release is breaking the build 🚨
## Version **15.9.15** of **semantic-release** was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="https://github.com/AtomLinter/linter-coffeelint/compare/master...AtomLinter:greenkeeper%2Fsemantic-release-15.9.15">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </th>
    <td>
      <a target=_blank href=https://github.com/semantic-release/semantic-release>semantic-release</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      15.9.14
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

semantic-release is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ✅ **ci/circleci: checkout_code:** Your tests passed on CircleCI! ([Details](https://circleci.com/gh/AtomLinter/linter-coffeelint/256?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ✅ **ci/circleci: lint:** Your tests passed on CircleCI! ([Details](https://circleci.com/gh/AtomLinter/linter-coffeelint/257?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ❌ **ci/circleci: beta:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/AtomLinter/linter-coffeelint/258?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ✅ **ci/circleci: stable:** Your tests passed on CircleCI! ([Details](https://circleci.com/gh/AtomLinter/linter-coffeelint/259?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
- ❌ **continuous-integration/travis-ci/push:** The Travis CI build failed ([Details](https://travis-ci.org/AtomLinter/linter-coffeelint/builds/427429205?utm_source=github_status&utm_medium=notification)).
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v15.9.15</strong>

<h2><a href="https://urls.greenkeeper.io/semantic-release/semantic-release/compare/v15.9.14...v15.9.15">15.9.15</a> (2018-09-11)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>package:</strong> update debug to version 4.0.0 (<a href="https://urls.greenkeeper.io/semantic-release/semantic-release/commit/7b8cd99">7b8cd99</a>)</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 1 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/semantic-release/semantic-release/commit/7b8cd9918b7c35fce5ed4791ae86bf51f8b5c668"><code>7b8cd99</code></a> <code>fix(package): update debug to version 4.0.0</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/semantic-release/semantic-release/compare/540d4fa764a822d3dfe6a8bac814e91af685e5c2...7b8cd9918b7c35fce5ed4791ae86bf51f8b5c668">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by UziTech**
@commitlint/cli@^7.1.2
@commitlint/config-conventional@^7.1.2
@commitlint/travis-cli@^7.1.2
husky@^1.1.0 closes #119
semantic-release@^15.9.16 closes #118
eslint@^5.6.1

### CODE REVIEW

**Comment by Arcanemagus** [comment]
I'd be hesitant to add the burden of maintaining custom scripts here if it can be avoided. Is there no way to ignore the spec files when running `coffeelint spec`, but still let them work for the specs?

**Comment by UziTech** [comment]
That is why I have been waiting on merging this PR.

I submitted a PR to https://github.com/atom/ci/pull/88 that would allow choosing which linter is used but until that PR is merged there is no way to prevent the build scripts from atom/ci from using coffeelint.

**Comment by UziTech** [comment]
@Arcanemagus it looks like you need to include node in arcanemagus/atom-docker-ci

Circle CI is failing because huskey needs node installed on Cleaning package

**Comment by UziTech** [comment]
I'm going to merge this so the build will stop failing, but I will keep an eye on my PR atom/ci#88 and remove the build scripts when I can.

**Comment by UziTech** [comment]
@Arcanemagus According to https://github.com/atom/ci/pull/88#issuecomment-444284456 the build scripts in atom/ci are supposed to be forked and not used directly. So it looks like we will need to keep the custom build scripts, unless you can think of a different way to keep the tests passing with the scripts from atom/ci.

I might just trim down the build scripts so they are easier to maintain.

**Pull request merged**
