### PR TITLE
update coffeelint

### PR DESCRIPTION
**Pull request by UziTech**

### CODE REVIEW

**Comment by UziTech** [comment]
@Arcanemagus looks like circle ci is erroring because it doesn't have permission to checkout the repo.

image

**Comment by Arcanemagus** [comment]
That doesn't make any sense... I'll check it out when I have a working computer.

**Comment by UziTech** [comment]
could be some bug in circle ci. It broke some time after I created this repo because the first commit passed then the second one broke and when I removed the second commit and force pushed with just the first commit it was still broke.

**Comment by Arcanemagus** [comment]
Hmm, I notice that this PR is from your fork instead of a branch on the repo itself, so the CircleCI build is happening under your user authentication. I wonder if that's currently broken?

**Comment by UziTech** [comment]
That is strange. It does have something to do with my account on Circle CI but I can't see what went wrong. Circle CI passed when I first created this PR then something broke and it won't pass anything on my account.

**Comment by Arcanemagus** [comment]
It could be something on CircleCI's side as you guessed earlier 🤷‍♂.

**Pull request closed without merging**
