### PR TITLE
Add linter-plus compatibility

### PR DESCRIPTION
**Pull request by AsaAyers**
With this PR linter-coffeelint works with [AtomLinter/linter](https://github.com/AtomLinter/linter) and [AtomLinter/linter-plus](https://github.com/AtomLinter/linter-plus).

Fixes https://github.com/iam4x/linter-plus-coffeelint/issues/2

This should replace the linter-plus-coffeelint repo.

### CODE REVIEW

**Comment by AsaAyers** [comment]
I see, this requires more work than I thought since my object currently extends from `Linter`:

    linterPath = atom.packages.getLoadedPackage('linter').path
    Linter = require "#{linterPath}/lib/linter"

I'll keep working on it.

**Comment by steelbrain** [comment]
Note: You can remove the `linter` compatibility as it's gonna show a warning to users as of 1st of next month to uninstall it and install linter-plus instead.

**Comment by AsaAyers** [comment]
Really? You're just going to nuke the whole existing community for no reason? This seems like a really stupid transition to me considering I had to dig through linter-plus code to figure out how to make the plugin compatible.

What happens to all of the other linter plugins? You're going to force all `linter-<whatever>` users to convert everything to `linter-plus-<whatever>`?

**Comment by AsaAyers** [comment]
https://github.com/iam4x/linter-plus-coffeelint/blob/master/lib/linter-plus-coffeelint.coffee#L22

^ This line is wrong, `linter-plus` doesn't provide an `Error` object to use so I had to go digging through code to figure out how to make it work.

**Comment by steelbrain** [comment]
The plugins won't become `linter-plus-<whatever>`, they'll stay `linter-<whatever>` but with a version number increment

**Comment by steelbrain** [comment]
and That linter isn't really a good thing to have directions from, as while linter-plus was evolving we made some API breaking changes, our current API can be considered stable. You should've had a look at atom-hack as mentioned by the README of linter-plus

**Comment by AsaAyers** [comment]
Yea, that code is very readable :-1: It's also a bad example because WTF is "hack"? If you want to have an example for people to copy from it needs to be well written, commented, maybe with a toy example. Like maybe a linter that forbids some arbitrary set of words.

Really, no one should have created linter-plus-coffeelint, instead it should have been a PR here. Now I'm simply trying to deal with the fragmentation of someone reinventing the wheel for no reason.

By the 1st of next month do you mean in 2 days? If so, why has no one bothered to mention that in an issue here? You are not ready to force users onto your brand new linter. The only reason I even considered adding compatibility is because I want to get rid of the unnecessary other project.

**Comment by steelbrain** [comment]
Hack is a language. Atom-Hack is a plugin that provides Linter API for Hack in Atom. and We just made that decision in the gitter room.

**Pull request merged**
